BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Produktkategorie" (
	"ID"	INTEGER NOT NULL,
	"Bezeichnung"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Zustand" (
	"ID"	INTEGER NOT NULL,
	"Bezeichnung"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Produktbild" (
	"ID"	INTEGER NOT NULL,
	"Bildpfad"	TEXT NOT NULL,
	"ProduktID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ProduktID") REFERENCES "Produkt"("ID")
);
CREATE TABLE IF NOT EXISTS "Benutzer" (
	"ID"	INTEGER NOT NULL,
	"Benutzername"	TEXT NOT NULL,
	"EMail"	TEXT,
	"Passwort"	TEXT NOT NULL,
	"PersonID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID")
);
CREATE TABLE IF NOT EXISTS "Person" (
	"ID"	INTEGER NOT NULL,
	"Vorname"	TEXT NOT NULL,
	"Nachname"	TEXT NOT NULL,
	"AdresseID"	INTEGER NOT NULL,
	"Telefonnummer"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("AdresseID") REFERENCES "Adresse"("ID")
);
CREATE TABLE IF NOT EXISTS "Adresse" (
	"ID"	INTEGER NOT NULL,
	"Strasse"	TEXT NOT NULL,
	"Hausnummer"	INTEGER NOT NULL,
	"PLZ"	INTEGER NOT NULL,
	"Ort"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
INSERT INTO "Adresse" VALUES (1,'fggrg',2,5145,'dgfhh');
INSERT INTO "Adresse" VALUES (2,'fggrg',2,5145,'dgfhh');
COMMIT;
