BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Adresse" (
	"ID"	INTEGER NOT NULL,
	"Strasse"	TEXT NOT NULL,
	"Hausnummer"	INTEGER NOT NULL,
	"PLZ"	INTEGER NOT NULL,
	"Ort"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Produktkategorie" (
	"ID"	INTEGER NOT NULL,
	"Bezeichnung"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Zustand" (
	"ID"	INTEGER NOT NULL,
	"Bezeichnung"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Benutzer" (
	"ID"	INTEGER NOT NULL,
	"Benutzername"	TEXT NOT NULL,
	"EMail"	TEXT NOT NULL,
	"Passwort"	TEXT NOT NULL,
	"PersonID"	INTEGER NOT NULL,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Produktbild" (
	"ID"	INTEGER NOT NULL,
	"Bildpfad"	TEXT NOT NULL,
	"ProduktID"	INTEGER NOT NULL,
	FOREIGN KEY("ProduktID") REFERENCES "Produkt"("ID"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
